/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "CalculadoraD.h"

struct {
	u_int vector_len;
	float *vector_val;
} vector;


void suma(CLIENT *clnt);
void resta(CLIENT *clnt);
void multiplicacion(CLIENT *clnt);
void division(CLIENT *clnt);
void promedio(CLIENT *clnt);
void potencia(CLIENT *clnt);
void raiz(CLIENT *clnt);

void
calculadorad_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	operadores  suma_1_arg;
	float  *result_2;
	operadores  resta_1_arg;
	float  *result_3;
	operadores  multiplicacion_1_arg;
	float  *result_4;
	operadores  division_1_arg;
	float  *result_5;
	operadores_promedio  promedio_1_arg;
	float  *result_6;
	operadores  potencia_1_arg;
	float  *result_7;
	operadores_raiz  raiz_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORAD, CALCULADORAD_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int opcion;
	printf("Elija opcion:\n1. Sumar\n2. Restar\n3. Multiplicar\n4. Dividir\n5. Promedio\n6. Potencia\n7. Raiz\n0. Salir\nOpcion: ");
	scanf("%d",&opcion);
	while(opcion != 0) {
		switch(opcion) {
			case 1:
				printf("Ha elegido suma: ");
				suma(clnt);

			break;
			case 2:
				printf("Ha elegido resta: ");
				resta(clnt);
			break;
			case 3:
				printf("Ha elegido multiplicacion: ");
				multiplicacion(clnt);
			break;
			case 4:
				printf("Ha elegido division: ");
				division(clnt);
			break;
			case 5:
				printf("Ha elegido promedio: ");
				promedio(clnt);
			break;
			case 6:
				printf("Ha elegido potencia: ");
				potencia(clnt);
			break;
			case 7:
				printf("Ha elegido raiz: ");
				raiz(clnt);
			break;
			default:
				printf("Opcion invalida.");
			break;
		}
		
		printf("Elija opcion:\n1. Sumar\n2. Restar\n3. Multiplicar\n4. Dividir\n5. Promedio\n 6. Potencia\n7. Raiz\n0. Salir\nOpcion: ");
		scanf("%d",&opcion);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void suma(CLIENT *clnt) {
	float  *result_1;
	operadores  suma_1_arg;

	printf("Ingrese numero A: ");
	scanf("%f",&suma_1_arg.a);
        
	printf("Ingrese numero B: ");
	scanf("%f",&suma_1_arg.b);
        
	result_1 = suma_1(&suma_1_arg,clnt);
	if(result_1==(float *) NULL) {
		clnt_perror (clnt,"Llamada fallida");
	}
	printf(" (%f + %f) = %f \n", suma_1_arg.a,suma_1_arg.b,*result_1);
}

void resta(CLIENT *clnt) {
	float  *result_2;
	operadores  resta_1_arg;

	printf("Ingrese numero A: ");
	scanf("%f",&resta_1_arg.a);
        
	printf("Ingrese numero B: ");
	scanf("%f",&resta_1_arg.b);
	
	result_2 = resta_1(&resta_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt,"Llamada fallida");
	}     
	printf(" (%f - %f) = %f \n", resta_1_arg.a,resta_1_arg.b,*result_2);
}

void multiplicacion(CLIENT *clnt) {
	float  *result_3;
	operadores  multiplicacion_1_arg;

	printf("Ingrese numero A: ");
	scanf("%f",&multiplicacion_1_arg.a);
        
	printf("Ingrese numero B: ");
	scanf("%f",&multiplicacion_1_arg.b);
        
	result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt,"Llamada fallida");
	}
	printf(" (%f * %f) = %f \n", multiplicacion_1_arg.a,multiplicacion_1_arg.b,*result_3);
}

void division(CLIENT *clnt) {
	float  *result_4;
	operadores  division_1_arg;

	printf("Ingrese numero A: ");
	scanf("%f",&division_1_arg.a);
        
	printf("Ingrese numero B: ");
	scanf("%f",&division_1_arg.b);
        
	result_4 = division_1(&division_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt,"Llamada fallida");
	}
	printf(" (%f / %f) = %f \n", division_1_arg.a,division_1_arg.b,*result_4);
}

void promedio(CLIENT *clnt) {
	float  *result_5;
	operadores_promedio  promedio_1_arg;

	printf("Ingrese cantidad de elementos: ");
	scanf("%d",&promedio_1_arg.tamano);

	promedio_1_arg.vector.vector_val = malloc(promedio_1_arg.tamano * sizeof(float));
	int i;
	for(i = 0; i < promedio_1_arg.tamano; i++) {
		printf("Ingrese valor #%d: ", i+1);
		scanf("%f",&promedio_1_arg.vector.vector_val[i]);
	}

	result_5 = promedio_1(&promedio_1_arg, clnt);
	if (result_5 == (float *) NULL) {
		clnt_perror (clnt,"Llamada fallida");
	}

	printf("Promedio de [");
	for(i = 0; i < promedio_1_arg.tamano; i++) {
		printf("%d ", promedio_1_arg.vector.vector_val[i]);
	}
	printf("] = %f \n", *result_5);
}

void potencia(CLIENT *clnt) {
	float  *result_6;
	operadores  potencia_1_arg;

	printf("Ingrese base: ");
	scanf("%f",&potencia_1_arg.a);
        
	printf("Ingrese exponente: ");
	scanf("%f",&potencia_1_arg.b);
        
	result_6 = potencia_1(&potencia_1_arg, clnt);
	if (result_6 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf(" (%f^%f) = %f \n", potencia_1_arg.a,potencia_1_arg.b,*result_6);
}

void raiz(CLIENT *clnt) {
	float  *result_7;
	operadores_raiz  raiz_1_arg;

	printf("Ingrese numero: ");
	scanf("%f",&raiz_1_arg.a);
        
	result_7 = raiz_1(&raiz_1_arg, clnt);
	if (result_7 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf(" (%f) = %f \n", raiz_1_arg.a, *result_7);
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadorad_1 (host);
exit (0);
}
