/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "CalculadoraD.h"
#include <math.h>

typedef struct {
	u_int vector_len;
	float *vector_val;
} vector;

float *
suma_1_svc(operadores *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("[Server] Peticion recibida: sumar");
	result = argp->a + argp->b;
	printf("[Server] Respuesta enviada.");	

	return &result;
}

float *
resta_1_svc(operadores *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("[Server] Peticion recibida: resta");
	result = argp->a - argp->b;
	printf("[Server] Respuesta enviada.");	

	return &result;
}

float *
multiplicacion_1_svc(operadores *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("[Server] Peticion recibida: multiplicacion");
	result = argp->a * argp->b;
	printf("[Server] Respuesta enviada.");	

	return &result;
}

float *
division_1_svc(operadores *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("[Server] Peticion recibida: division");
	result = argp->a / argp->b;
	printf("[Server] Respuesta enviada.");	

	return &result;
}

float *
promedio_1_svc(operadores_promedio *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("[Server] Peticion recibida: promedio");
	float acumulador = 0;
	
	int i;
	for(i = 0; i < argp->tamano; i++) {
		acumulador += argp->vector.vector_val[i];
	}
	result = acumulador / argp->tamano;
	printf("[Server] Respuesta enviada.");	

	return &result;
}

float *
potencia_1_svc(operadores *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("[Server] Peticion recibida: potencia");
	result = pow(argp->a, argp->b);
	printf("[Server] Respuesta enviada.");	

	return &result;
}

float *
raiz_1_svc(operadores_raiz *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("[Server] Peticion recibida: raiz");
	result = sqrt(argp->a);
	printf("[Server] Respuesta enviada.");	

	return &result;
}
